#!/usr/bin/env bash
# ProtoGC Pico SDK syntax/AST compile check.
#
# Compiles check_pico.cpp (which includes src/pgc_pico.cpp) AND check.cpp
# (the shared API smoke TU — the full library headers) against the REAL
# Pico SDK headers with the same arm-none-eabi-g++ flags the RP2350-ProtoGPU
# firmware build uses. No code is linked or executed (-fsyntax-only).
#
# Flag provenance (2026-07-19), from the sibling firmware repo:
#   cd /home/polar/MCUGPU/RP2350-ProtoGPU/build && \
#   make -n -B -f CMakeFiles/protogl_gpu.dir/build.make \
#       CMakeFiles/protogl_gpu.dir/src/memory/mem_tier.cpp.o
# (PICO_BOARD=pico2, Pico SDK 2.3.0, arm-gnu-toolchain 13.3.rel1). The CMake-
# generated pico_base headers (pico/version.h, pico/config_autogen.h) are
# reproduced by the shim step below so this script needs only the SDK tree.
#
# Prerequisites (either missing => ERROR + exit 1, NOT a silent skip — same
# policy as run_check.sh's missing-compiler path, so CI cannot pass without
# having compiled anything):
#   * Pico SDK:  $PICO_SDK_PATH (default ~/pico/pico-sdk)
#   * Toolchain: $TOOLCHAIN_BIN/arm-none-eabi-g++ (default
#     ~/toolchains/arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-eabi/bin),
#     falling back to arm-none-eabi-g++ on PATH
#
# Usage (from the repo root or anywhere else):
#   ./tests/syntax_check/run_check_pico.sh
#
# Exit code: 0 if the TU compiles clean, 1 otherwise (including missing deps).

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
PICO_SDK_PATH="${PICO_SDK_PATH:-$HOME/pico/pico-sdk}"
TOOLCHAIN_BIN="${TOOLCHAIN_BIN:-$HOME/toolchains/arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-eabi/bin}"
BUILD_DIR="${BUILD_DIR:-$REPO_ROOT/build/pico-syntax-check}"

echo "ProtoGC Pico syntax check"
echo "  SDK:      $PICO_SDK_PATH"

# -------------------------------------------------------------- prerequisites

if [ ! -d "$PICO_SDK_PATH/src" ]; then
    echo "ERROR: Pico SDK not found at $PICO_SDK_PATH (set PICO_SDK_PATH to override)"
    exit 1
fi

CXX="$TOOLCHAIN_BIN/arm-none-eabi-g++"
if [ ! -x "$CXX" ]; then
    CXX="$(command -v arm-none-eabi-g++ || true)"
fi
if [ -z "$CXX" ]; then
    echo "ERROR: arm-none-eabi-g++ not found in $TOOLCHAIN_BIN or on PATH"
    echo "       (set TOOLCHAIN_BIN to the toolchain bin dir to override)"
    exit 1
fi
echo "  compiler: $CXX"

# ------------------------------------------------- generated-header shim ----
# pico.h includes pico/version.h and pico/config.h -> pico/config_autogen.h,
# which a CMake build generates into <build>/generated/pico_base. Reproduce
# them here from SDK sources so no configured firmware build dir is needed.

SHIM_DIR="$BUILD_DIR/shim"
mkdir -p "$SHIM_DIR/pico"

SDK_VER_CMAKE="$PICO_SDK_PATH/pico_sdk_version.cmake"
sdk_version_part() {
    # $1 = MAJOR|MINOR|REVISION; prints the first set(...) value, else empty
    sed -n "s/^set(PICO_SDK_VERSION_$1 \\([0-9][0-9]*\\)).*/\\1/p" "$SDK_VER_CMAKE" | head -n 1
}
VER_MAJOR="$(sdk_version_part MAJOR)";    VER_MAJOR="${VER_MAJOR:-0}"
VER_MINOR="$(sdk_version_part MINOR)";    VER_MINOR="${VER_MINOR:-0}"
VER_REVISION="$(sdk_version_part REVISION)"; VER_REVISION="${VER_REVISION:-0}"

cat > "$SHIM_DIR/pico/version.h" <<EOF
/* Autogenerated by run_check_pico.sh from pico_sdk_version.cmake — do not edit. */
#ifndef _PICO_VERSION_H
#define _PICO_VERSION_H
#define PICO_SDK_VERSION_MAJOR    $VER_MAJOR
#define PICO_SDK_VERSION_MINOR    $VER_MINOR
#define PICO_SDK_VERSION_REVISION $VER_REVISION
#define PICO_SDK_VERSION_STRING   "$VER_MAJOR.$VER_MINOR.$VER_REVISION"
#endif
EOF

# Mirrors the firmware build's config_autogen.h (board header + CMSIS
# exception renaming), with SDK-relative includes instead of absolute paths.
cat > "$SHIM_DIR/pico/config_autogen.h" <<'EOF'
/* Autogenerated by run_check_pico.sh — mirrors the CMake-generated
 * config_autogen.h (PICO_CONFIG_HEADER_FILES) of RP2350-ProtoGPU. */
#include <boards/pico2.h>
#include <cmsis/rename_exceptions.h>
EOF

# ------------------------------------------------------------------ flags ---
# CPU/ABI, language and diagnostic flags: verbatim from the firmware compile
# line (dependency-file and output flags omitted, -fsyntax-only added).

CXXFLAGS="-mcpu=cortex-m33 -mthumb -march=armv8-m.main+fp+dsp -mcmse -mfloat-abi=softfp"
CXXFLAGS="$CXXFLAGS -std=gnu++17 -Wall -Wextra -Wno-unused-parameter"
CXXFLAGS="$CXXFLAGS -O2 -DNDEBUG -ffast-math -fno-math-errno"
CXXFLAGS="$CXXFLAGS -fno-exceptions -fno-unwind-tables -fno-rtti -fno-use-cxa-atexit"
CXXFLAGS="$CXXFLAGS -ffunction-sections -fdata-sections"
CXXFLAGS="$CXXFLAGS -fsyntax-only"

# Preprocessor defines: verbatim from the firmware compile line, except
# PICO_TARGET_NAME (meaningless for this TU).
DEFINES=(
    LIB_BOOT_STAGE2_HEADERS=1 LIB_PICO_ATOMIC=1 LIB_PICO_BIT_OPS=1
    LIB_PICO_BIT_OPS_PICO=1 LIB_PICO_CLIB_INTERFACE=1 LIB_PICO_CRT0=1
    LIB_PICO_CXX_OPTIONS=1 LIB_PICO_DIVIDER=1 LIB_PICO_DIVIDER_COMPILER=1
    LIB_PICO_DOUBLE=1 LIB_PICO_DOUBLE_PICO=1 LIB_PICO_DOUBLE_PICO_DCP=1
    LIB_PICO_FLASH=1 LIB_PICO_FLOAT=1 LIB_PICO_FLOAT_PICO=1
    LIB_PICO_FLOAT_PICO_VFP=1 LIB_PICO_I2C_SLAVE=1 LIB_PICO_INT64_OPS=1
    LIB_PICO_INT64_OPS_COMPILER=1 LIB_PICO_MALLOC=1 LIB_PICO_MEM_OPS=1
    LIB_PICO_MEM_OPS_COMPILER=1 LIB_PICO_MULTICORE=1
    LIB_PICO_NEWLIB_INTERFACE=1 LIB_PICO_PLATFORM=1 LIB_PICO_PLATFORM_COMMON=1
    LIB_PICO_PLATFORM_COMPILER=1 LIB_PICO_PLATFORM_PANIC=1
    LIB_PICO_PLATFORM_SECTIONS=1 LIB_PICO_PRINTF=1 LIB_PICO_PRINTF_PICO=1
    LIB_PICO_RUNTIME=1 LIB_PICO_RUNTIME_INIT=1 LIB_PICO_STANDARD_BINARY_INFO=1
    LIB_PICO_STANDARD_LINK=1 LIB_PICO_STDIO=1 LIB_PICO_STDIO_UART=1
    LIB_PICO_STDLIB=1 LIB_PICO_SYNC=1 LIB_PICO_SYNC_CRITICAL_SECTION=1
    LIB_PICO_SYNC_MUTEX=1 LIB_PICO_SYNC_SEM=1 LIB_PICO_TIME=1
    LIB_PICO_TIME_ADAPTER=1 LIB_PICO_UTIL=1
    PICO_32BIT=1 'PICO_BOARD="pico2"' PICO_BUILD=1
    'PICO_CMAKE_BUILD_TYPE="Release"' PICO_COPY_TO_RAM=0
    PICO_CXX_ENABLE_EXCEPTIONS=0 PICO_DEFAULT_UART=0 PICO_DEFAULT_UART_RX_PIN=17
    PICO_DEFAULT_UART_TX_PIN=16 PICO_NO_FLASH=0 PICO_NO_HARDWARE=0
    PICO_ON_DEVICE=1 PICO_RP2350=1 PICO_THREAD_LOCAL_EMUTLS_CONFIRMED=1
    PICO_THREAD_LOCAL_MODE_PER_THREAD=1 PICO_USE_BLOCKED_RAM=0 PICO_XIP_RAM=0
)

# SDK include dirs: the firmware compile line's -isystem set (SDK-relative),
# plus src/rp2_common/cmsis/include (the firmware's config_autogen.h reaches
# rename_exceptions.h by absolute path instead) and the shim dir (which
# replaces <build>/generated/pico_base).
INCLUDES=(
    src/boards/include
    src/common/boot_picobin_headers/include
    src/common/boot_picoboot_headers/include
    src/common/hardware_claim/include
    src/common/pico_base_headers/include
    src/common/pico_binary_info/include
    src/common/pico_bit_ops_headers/include
    src/common/pico_divider_headers/include
    src/common/pico_stdlib_headers/include
    src/common/pico_sync/include
    src/common/pico_time/include
    src/common/pico_util/include
    src/rp2350/boot_stage2/include
    src/rp2350/hardware_regs/include
    src/rp2350/hardware_structs/include
    src/rp2350/pico_platform/include
    src/rp2_common/boot_bootrom_headers/include
    src/rp2_common/cmsis/include
    src/rp2_common/hardware_adc/include
    src/rp2_common/hardware_base/include
    src/rp2_common/hardware_boot_lock/include
    src/rp2_common/hardware_clocks/include
    src/rp2_common/hardware_dcp/include
    src/rp2_common/hardware_divider/include
    src/rp2_common/hardware_dma/include
    src/rp2_common/hardware_flash/include
    src/rp2_common/hardware_gpio/include
    src/rp2_common/hardware_i2c/include
    src/rp2_common/hardware_irq/include
    src/rp2_common/hardware_pio/include
    src/rp2_common/hardware_pll/include
    src/rp2_common/hardware_rcp/include
    src/rp2_common/hardware_resets/include
    src/rp2_common/hardware_spi/include
    src/rp2_common/hardware_sync/include
    src/rp2_common/hardware_sync_spin_lock/include
    src/rp2_common/hardware_ticks/include
    src/rp2_common/hardware_timer/include
    src/rp2_common/hardware_uart/include
    src/rp2_common/hardware_vreg/include
    src/rp2_common/hardware_watchdog/include
    src/rp2_common/hardware_xip_cache/include
    src/rp2_common/hardware_xosc/include
    src/rp2_common/pico_bootrom/include
    src/rp2_common/pico_cxx_options/include
    src/rp2_common/pico_double/include
    src/rp2_common/pico_flash/include
    src/rp2_common/pico_float/include
    src/rp2_common/pico_i2c_slave/include
    src/rp2_common/pico_malloc/include
    src/rp2_common/pico_multicore/include
    src/rp2_common/pico_platform_common/include
    src/rp2_common/pico_platform_compiler/include
    src/rp2_common/pico_platform_panic/include
    src/rp2_common/pico_platform_sections/include
    src/rp2_common/pico_printf/include
    src/rp2_common/pico_runtime/include
    src/rp2_common/pico_runtime_init/include
    src/rp2_common/pico_stdio/include
    src/rp2_common/pico_stdio_uart/include
    src/rp2_common/pico_thread_local/include
    src/rp2_common/pico_time_adapter/include
)

FLAGS=( )
for d in "${DEFINES[@]}";  do FLAGS+=( "-D$d" ); done
FLAGS+=( -isystem "$SHIM_DIR" )
for d in "${INCLUDES[@]}"; do FLAGS+=( -isystem "$PICO_SDK_PATH/$d" ); done

# ------------------------------------------------------------------ check ---

TUS="check_pico.cpp check.cpp"
FAILURES=0
for tu in $TUS; do
    out=$("$CXX" $CXXFLAGS "${FLAGS[@]}" "$SCRIPT_DIR/$tu" 2>&1)
    status=$?
    if [ "$status" -eq 0 ] && [ -z "$out" ]; then
        echo "[arm-none-eabi rp2350] PASS $tu"
    else
        echo "[arm-none-eabi rp2350] FAIL $tu"
        [ -n "$out" ] && echo "$out" | sed 's/^/    /'
        FAILURES=$((FAILURES + 1))
    fi
done

echo
if [ "$FAILURES" -eq 0 ]; then
    echo "RESULT: PASS"
    exit 0
else
    echo "RESULT: FAIL ($FAILURES failing TU(s))"
    exit 1
fi
