#pragma once
// Minimal sdkconfig.h stub for the ProtoGC syntax/AST compile check.
//
// This is NOT a full ESP-IDF configuration. It defines only the CONFIG_*
// macros that ESP-IDF v6.0.2 headers (FreeRTOS config, portmacros, heap,
// esp_hw_support, esp_system, soc) reference while compiling ProtoGC's
// headers with -fsyntax-only. Values mirror a typical ESP32-S3 / ESP32-P4
// default project.
//
// IMPORTANT: macros that IDF headers test with #ifdef (rather than #if)
// must stay UNDEFINED here — defining them to 0 would still enable the
// guarded block. Those are listed at the bottom for reference.

// ---- esp system / common ----
#define CONFIG_IDF_TARGET_ESP32S3 1
#define CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ 240
#define CONFIG_ESP_INT_WDT_TIMEOUT_MS 300
#define CONFIG_ESP_TRACE_ENABLE 0
#define CONFIG_ESP_TRACE_TRANSPORT_APPTRACE 0
#define CONFIG_SECURE_ENABLE_TEE 0

// ---- compiler / libc ----
#define CONFIG_COMPILER_OPTIMIZATION_NONE 0
#define CONFIG_COMPILER_STACK_CHECK_MODE_NONE 1
#define CONFIG_STACK_CHECK_ALL 0
#define CONFIG_STACK_CHECK_STRONG 0
#define CONFIG_LIBC_NEWLIB 1

// ---- heap ----
#define CONFIG_HEAP_HAS_EXEC_HEAP 1
#define CONFIG_HEAP_PLACE_FUNCTION_INTO_FLASH 0
// CONFIG_HEAP_USE_HOOKS: #ifdef-guarded -> intentionally NOT defined

// ---- FreeRTOS: scheduler ----
#define CONFIG_FREERTOS_HZ 100
#define CONFIG_FREERTOS_NUMBER_OF_CORES 2
#define CONFIG_FREERTOS_UNICORE 0
#define CONFIG_FREERTOS_SMP 0
// CONFIG_FREERTOS_OPTIMIZED_SCHEDULER is #ifdef-guarded -> intentionally NOT
// defined (real multicore targets leave it off; the upstream kernel #errors
// if it is set with >1 core).
#define CONFIG_FREERTOS_USE_TICKLESS_IDLE 0
#define CONFIG_FREERTOS_IDLE_TIME_BEFORE_SLEEP 3
#define CONFIG_FREERTOS_USE_PASSIVE_IDLE_HOOK 0
#define CONFIG_FREERTOS_IDLE_TASK_STACKSIZE 1536
#define CONFIG_FREERTOS_ISR_STACKSIZE 1536
#define CONFIG_FREERTOS_MAX_TASK_NAME_LEN 16
#define CONFIG_FREERTOS_THREAD_LOCAL_STORAGE_POINTERS 1
#define CONFIG_FREERTOS_QUEUE_REGISTRY_SIZE 0
#define CONFIG_FREERTOS_TASK_NOTIFICATION_ARRAY_ENTRIES 1
#define CONFIG_FREERTOS_USE_TRACE_FACILITY 0
#define CONFIG_FREERTOS_CORETIMER_0 1
#define CONFIG_FREERTOS_CORETIMER_1 0
#define CONFIG_FREERTOS_SYSTICK_USES_CCOUNT 1
#define CONFIG_FREERTOS_WATCHPOINT_END_OF_STACK 0
// CONFIG_FREERTOS_CHECK_PORT_CRITICAL_COMPLIANCE: #ifdef-guarded -> NOT defined

// ---- FreeRTOS: hooks / stack overflow ----
#define CONFIG_FREERTOS_USE_IDLE_HOOK 0
#define CONFIG_FREERTOS_USE_TICK_HOOK 0
#define CONFIG_FREERTOS_CHECK_STACKOVERFLOW_NONE 1
#define CONFIG_FREERTOS_CHECK_STACKOVERFLOW_PTRVAL 0
#define CONFIG_FREERTOS_CHECK_STACKOVERFLOW_CANARY 0
#define CONFIG_FREERTOS_ENABLE_STATIC_TASK_CLEAN_UP 0
#define CONFIG_FREERTOS_TASK_FUNCTION_WRAPPER 0
#define CONFIG_FREERTOS_DEBUG_OCDAWARE 0
#define CONFIG_FREERTOS_CHECK_MUTEX_GIVEN_BY_OWNER 0

// ---- FreeRTOS: compat / misc ----
#define CONFIG_FREERTOS_ENABLE_BACKWARD_COMPATIBILITY 0
#define CONFIG_FREERTOS_USE_APPLICATION_TASK_TAG 0
#define CONFIG_FREERTOS_USE_LIST_DATA_INTEGRITY_CHECK_BYTES 0
#define CONFIG_FREERTOS_RUN_TIME_COUNTER_TYPE_U32 1
#define CONFIG_FREERTOS_RUN_TIME_COUNTER_TYPE_U64 0

// ---- FreeRTOS: software timers ----
#define CONFIG_FREERTOS_USE_TIMERS 0
#define CONFIG_FREERTOS_TIMER_TASK_PRIORITY 1
#define CONFIG_FREERTOS_TIMER_QUEUE_LENGTH 10
#define CONFIG_FREERTOS_TIMER_TASK_STACK_DEPTH 2048
#define CONFIG_FREERTOS_TIMER_SERVICE_TASK_NAME "Tmr Svc"
#define CONFIG_FREERTOS_TIMER_SERVICE_TASK_CORE_AFFINITY 0x7FFFFFFF

// ---- #ifdef-guarded macros that must NOT be defined (reference only) ----
// CONFIG_FREERTOS_GENERATE_RUN_TIME_STATS
// CONFIG_FREERTOS_USE_STATS_FORMATTING_FUNCTIONS
// CONFIG_FREERTOS_VTASKLIST_INCLUDE_COREID
// CONFIG_FREERTOS_TLSP_DELETION_CALLBACKS
// CONFIG_FREERTOS_OPTIMIZED_SCHEDULER
// CONFIG_FREERTOS_CHECK_PORT_CRITICAL_COMPLIANCE
// CONFIG_HEAP_USE_HOOKS
// CONFIG_IDF_CI_BUILD
// CONFIG_SPIRAM_WORKAROUND_NEED_VOLATILE_SPINLOCK
